# Generated by Django 3.2.3 on 2021-06-08 15:05

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contents', models.CharField(max_length=200, null=True)),
                ('region', models.CharField(max_length=200)),
                ('totalMember', models.IntegerField(null=True)),
                ('kakao_url', models.CharField(max_length=200)),
                ('onOff', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=200, null=True)),
                ('oneLine', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('study_duration', models.CharField(max_length=200, null=True)),
                ('board_text', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('count', models.IntegerField(null=True)),
                ('is_finish', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
