# Generated by Django 3.2.3 on 2021-06-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnA2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study', models.IntegerField()),
                ('contents', models.CharField(max_length=500)),
                ('writer', models.CharField(max_length=500)),
            ],
        ),
    ]
