# Generated by Django 3.2.3 on 2021-06-02 16:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mystudy_board_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystudy',
            name='board_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
