# Generated by Django 3.2.3 on 2021-06-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_mystudy_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystudy',
            name='img_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
