# Generated by Django 3.2.3 on 2021-06-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_mystudy_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystudy',
            name='study_duration',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
