# Generated by Django 3.2.3 on 2021-06-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_mystudy_study_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystudy',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mystudy',
            name='totalMember',
            field=models.IntegerField(null=True),
        ),
    ]
