# Generated by Django 3.2.3 on 2021-06-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_qna1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystudy',
            name='contents',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
